### ISSUE TITLE
Is this js useable at any stage?

### ISSUE THREAD

**Issue by ahmadalibaloch** [elmarquez/section#1]

**Comment by elmarquez** [comment]
Ahmad;

Yes, it is usable right now.  If you look in the test/fixtures folder, you will see an HTML page with a working example.

I have a number of updates coming in a few days, so you can expect that the model definition will evolve quite a bit. Please let me know if there are any particular features you might be interested in seeing.

Davis

**Comment by elmarquez** [comment]
One more thing I should mention -- I typically tag all stable releases, so look under the branch/tags drop down on the main page for the list of released versions.

**Comment by ahmadalibaloch** [comment]
thanks. I have managed to build it. It was missing all the references to the libraries like three.js and OpenJSCAD.org in its test and source.

**Comment by elmarquez** [comment]
Sorry, that's right ... I've updated the documentation in the develop branch and pushed a first tagged release.
