### ISSUE TITLE
2D to 3D like wanaplan

### ISSUE THREAD

**Issue by ahmadalibaloch** [elmarquez/section#2]
I want and am ready to help in developing feature which builds a house model from 2D drawing as we can see in https://github.com/wanadev/WanaplanAPI.

**Comment by elmarquez** [comment]
I do have need for a basic 3D building editor but I won't be making that part of this particular project. Section will stay focused on making a easy-to-use building floor, wall, roof model/diagram generator.

Have you looked at the Threejs Editor?  http://mrdoob.github.io/three.js/editor/
